/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controlador.Controller;
import Parseador.Parser;
import java.text.DecimalFormat;


public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private Controller control;//Se comunica con el controlador para llevar a cabo las funcionalidades requeridas
    private Parser mapCartas;//Llama al parser para elaborar el map con todas las cartas
    private char fase = 'P';//Se indica que fase del juego estan
    private int numJugador;
    private int numFold;
    private boolean[] cartasFijadas = {false, false, false, false, false, false,false, false, false,false, false, false,false, false, false};
    
    public GUI() {
        initComponents();
        mapCartas = new Parser();
        control = new Controller(mapCartas.getCartas(), fase);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCEquity = new javax.swing.JButton();
        jTextField_Player1 = new javax.swing.JTextField();
        jTextField_Player2 = new javax.swing.JTextField();
        jTextField_Player3 = new javax.swing.JTextField();
        jTextField_Player4 = new javax.swing.JTextField();
        jTextField_Player5 = new javax.swing.JTextField();
        jTextField_Player6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButtonFold2 = new javax.swing.JButton();
        jButtonFold3 = new javax.swing.JButton();
        jButtonFold4 = new javax.swing.JButton();
        jButtonFold5 = new javax.swing.JButton();
        jButtonFold6 = new javax.swing.JButton();
        jButtonFold1 = new javax.swing.JButton();
        jButton_Aplicar = new javax.swing.JButton();
        jButtonRiver = new javax.swing.JButton();
        jButtonTurn = new javax.swing.JButton();
        jButtonFlop3 = new javax.swing.JButton();
        jButtonFLop2 = new javax.swing.JButton();
        jButtonFlop1 = new javax.swing.JButton();
        jButtonPlayer2_2 = new javax.swing.JButton();
        jButtonPlayer2_1 = new javax.swing.JButton();
        jButtonPlayer6_2 = new javax.swing.JButton();
        jButtonPlayer6_1 = new javax.swing.JButton();
        jButtonPlayer5_2 = new javax.swing.JButton();
        jButtonPlayer5_1 = new javax.swing.JButton();
        jButtonPlayer4_2 = new javax.swing.JButton();
        jButtonPlayer4_1 = new javax.swing.JButton();
        jButtonPlayer3_1 = new javax.swing.JButton();
        jButtonPlayer3_2 = new javax.swing.JButton();
        jButtonPlayer1_1 = new javax.swing.JButton();
        jButtonPlayer1_2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCEquity.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCEquity.setText("Calcular Equity");
        jButtonCEquity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCEquityActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCEquity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 140, 30));
        jButtonCEquity.setBorder(null);
        getContentPane().add(jTextField_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, -1));
        getContentPane().add(jTextField_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, 200, -1));
        getContentPane().add(jTextField_Player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 200, -1));
        getContentPane().add(jTextField_Player4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, 200, -1));
        getContentPane().add(jTextField_Player5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 200, -1));

        jTextField_Player6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Player6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Player6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 200, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 30));
        jTextField1.setVisible(false);

        jButtonFold2.setText("FOLD");
        jButtonFold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 80, -1));

        jButtonFold3.setText("FOLD");
        jButtonFold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 630, 80, -1));

        jButtonFold4.setText("FOLD");
        jButtonFold4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 80, -1));

        jButtonFold5.setText("FOLD");
        jButtonFold5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 80, -1));

        jButtonFold6.setText("FOLD");
        jButtonFold6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 80, -1));

        jButtonFold1.setText("FOLD");
        jButtonFold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, -1));

        jButton_Aplicar.setText("Aplicar");
        jButton_Aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AplicarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 30));
        jButton_Aplicar.setBorder(null);
        jButton_Aplicar.setVisible(false);

        jButtonRiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonRiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRiverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 120, 160));
        jButtonRiver.setBorder(null);

        jButtonTurn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 120, 160));
        jButtonTurn.setBorder(null);

        jButtonFlop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonFlop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlop3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFlop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 120, 160));
        jButtonFlop3.setBorder(null);

        jButtonFLop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonFLop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLop2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFLop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 160));
        jButtonFLop2.setBorder(null);

        jButtonFlop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonFlop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlop1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFlop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 120, 160));
        jButtonFlop1.setBorder(null);

        jButtonPlayer2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer2_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 100, 130));
        jButtonPlayer2_2.setBorder(null);

        jButtonPlayer2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer2_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 100, 130));
        jButtonPlayer2_1.setBorder(null);

        jButtonPlayer6_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer6_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 100, 130));
        jButtonPlayer6_2.setBorder(null);

        jButtonPlayer6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer6_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 100, 130));
        jButtonPlayer6_1.setBorder(null);

        jButtonPlayer5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer5_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 100, 130));
        jButtonPlayer5_2.setBorder(null);

        jButtonPlayer5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer5_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 100, 130));
        jButtonPlayer5_1.setBorder(null);

        jButtonPlayer4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer4_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 100, 130));
        jButtonPlayer4_2.setBorder(null);

        jButtonPlayer4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer4_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 100, 130));
        jButtonPlayer4_1.setBorder(null);

        jButtonPlayer3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer3_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 100, 130));
        jButtonPlayer3_1.setBorder(null);

        jButtonPlayer3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer3_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 100, 130));
        jButtonPlayer3_2.setBorder(null);

        jButtonPlayer1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer1_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 130));
        jButtonPlayer1_1.setBorder(null);

        setVisible(false);
        jButtonPlayer1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer1_2.setText("jButton2");
        jButtonPlayer1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer1_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 100, 130));
        jButtonPlayer1_2.setBorder(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 750, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1150, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayer3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer3_2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[5]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 5;
        }
    }//GEN-LAST:event_jButtonPlayer3_2ActionPerformed

    private void jTextField_Player6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Player6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Player6ActionPerformed

    private void jButtonPlayer1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer1_1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[0]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 0;
        }
    }//GEN-LAST:event_jButtonPlayer1_1ActionPerformed

    private void jButtonPlayer1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer1_2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[1]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 1;
        }
    }//GEN-LAST:event_jButtonPlayer1_2ActionPerformed

    private void jButtonPlayer2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer2_1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[2]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 2;
        }
    }//GEN-LAST:event_jButtonPlayer2_1ActionPerformed

    private void jButtonPlayer2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer2_2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[3]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 3;
        }
    }//GEN-LAST:event_jButtonPlayer2_2ActionPerformed

    private void jButtonPlayer3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer3_1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[4]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 4;
        }
    }//GEN-LAST:event_jButtonPlayer3_1ActionPerformed

    private void jButtonPlayer4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer4_1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[6]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 6;
        }
    }//GEN-LAST:event_jButtonPlayer4_1ActionPerformed

    private void jButtonPlayer4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer4_2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[7]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 7;
        }
    }//GEN-LAST:event_jButtonPlayer4_2ActionPerformed

    private void jButtonPlayer6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer6_1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[10]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 10;
        }
        
    }//GEN-LAST:event_jButtonPlayer6_1ActionPerformed

    private void jButtonPlayer5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer5_1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[8]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 8;
        }
    }//GEN-LAST:event_jButtonPlayer5_1ActionPerformed

    private void jButtonPlayer5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer5_2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[9]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 9;
        }
    }//GEN-LAST:event_jButtonPlayer5_2ActionPerformed

    private void jButtonPlayer6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer6_2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[11]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 11;
        }
    }//GEN-LAST:event_jButtonPlayer6_2ActionPerformed

    private void jButtonFlop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlop1ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[12]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 12;
        }
    }//GEN-LAST:event_jButtonFlop1ActionPerformed

    private void jButtonFLop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLop2ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[13]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 13;
        }
        
    }//GEN-LAST:event_jButtonFLop2ActionPerformed

    private void jButtonFlop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlop3ActionPerformed
        // TODO add your handling code here:
        if(!cartasFijadas[14]){
            jTextField1.setVisible(true);
            jButton_Aplicar.setVisible(true);
            this.numJugador = 14;
        }
    }//GEN-LAST:event_jButtonFlop3ActionPerformed

    private void jButtonTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnActionPerformed
        // TODO add your handling code here:
        jTextField1.setVisible(true);
        jButton_Aplicar.setVisible(true);
        this.numJugador = 15;
    }//GEN-LAST:event_jButtonTurnActionPerformed

    private void jButtonRiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRiverActionPerformed
        // TODO add your handling code here:
        jTextField1.setVisible(true);
        jButton_Aplicar.setVisible(true);
        this.numJugador = 16;
    }//GEN-LAST:event_jButtonRiverActionPerformed

    private void jButton_AplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AplicarActionPerformed
        // TODO add your handling code here:
        if(this.numJugador <= 11){
            if(jTextField1.getText().equals("")){
                String cadena = control.generoCartaAleatorio(this.numJugador);
                establecerIcono(cadena);
                jTextField1.setVisible(false);
                jButton_Aplicar.setVisible(false);
            }
            else if(existeCarta(jTextField1.getText())){
                String cadena = control.generoCarta(this.numJugador, jTextField1.getText());
                establecerIcono(cadena);
                jTextField1.setVisible(false);
                jButton_Aplicar.setVisible(false);
            }
            else{
                jTextField1.setText("Carta no existe");
            }
        }
        else{
            if(jTextField1.getText().equals("")){
                String cadena = control.generoCartaAleatorioPostFlop(this.numJugador);
                establecerIcono(cadena);
                jTextField1.setVisible(false);
                jButton_Aplicar.setVisible(false);
            }
            else if(existeCarta(jTextField1.getText())){
                String cadena = control.generoCartaPostFlop(this.numJugador, jTextField1.getText());
                establecerIcono(cadena);
                jTextField1.setVisible(false);
                jButton_Aplicar.setVisible(false);
            }
            else{
                jTextField1.setText("Carta no existe");
            }
        }
        
    }//GEN-LAST:event_jButton_AplicarActionPerformed

    private void jButtonCEquityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCEquityActionPerformed
        // TODO add your handling code here:
        double[] equity = new double[6];
        control.inicializarWins();
        if(cartasSuficientes()){
            equity = this.control.calcularEquity();
            establecerEquity(equity);
        }
    }//GEN-LAST:event_jButtonCEquityActionPerformed

    private void jButtonFold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold1ActionPerformed
        // TODO add your handling code here:
        this.numFold = 0;
        foldear();
        jTextField_Player1.setVisible(false);
    }//GEN-LAST:event_jButtonFold1ActionPerformed

    private void jButtonFold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold2ActionPerformed
        // TODO add your handling code here:
        this.numFold = 1;
        foldear();
        jTextField_Player2.setVisible(false);
    }//GEN-LAST:event_jButtonFold2ActionPerformed

    private void jButtonFold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold3ActionPerformed
        // TODO add your handling code here:
        
        this.numFold = 2;
        foldear();
        jTextField_Player3.setVisible(false);
    }//GEN-LAST:event_jButtonFold3ActionPerformed

    private void jButtonFold4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold4ActionPerformed
        // TODO add your handling code here:
        this.numFold = 3;
        foldear();
        jTextField_Player4.setVisible(false);
    }//GEN-LAST:event_jButtonFold4ActionPerformed

    private void jButtonFold5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold5ActionPerformed
        // TODO add your handling code here:
        this.numFold = 4;
        foldear();
        jTextField_Player5.setVisible(false);
    }//GEN-LAST:event_jButtonFold5ActionPerformed

    private void jButtonFold6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold6ActionPerformed
        // TODO add your handling code here:
        this.numFold = 5;
        foldear();
        jTextField_Player6.setVisible(false);
    }//GEN-LAST:event_jButtonFold6ActionPerformed
    
    private void foldear(){
        control.foldear(numFold);
    }
    private void establecerEquity(double[] aux){
         DecimalFormat df = new DecimalFormat("#.000");
        if(aux[0] != -1)           
            jTextField_Player1.setText(Double.toString(aux[0]));
        if(aux[1] != -1)
            jTextField_Player2.setText(Double.toString(aux[1]));
        if(aux[2] != -1)
            jTextField_Player3.setText(Double.toString(aux[2]));
        if(aux[3] != -1)
            jTextField_Player4.setText(Double.toString(aux[3]));
        if(aux[4] != -1)
            jTextField_Player5.setText(Double.toString(aux[4]));
        if(aux[5] != -1)
            jTextField_Player6.setText(Double.toString(aux[5]));
        
    }
    
    private boolean cartasSuficientes(){
        
        if(!cartasFijadas[0]){
            return false;
        }
        else if(!cartasFijadas[1]){
            return false;
        }
        else if (!cartasFijadas[2]){
            return false;
        }
         else if (!cartasFijadas[3]){
            return false;
        }
        else if (!cartasFijadas[4]){
            return false;
        }
        else if (!cartasFijadas[5]){
            return false;
        }
        else if (!cartasFijadas[6]){
            return false;
        } 
        else if (!cartasFijadas[7]){
            return false;
        } 
        else if (!cartasFijadas[8]){
            return false;
        } 
        else if (!cartasFijadas[9]){
            return false;
        }
        else if (!cartasFijadas[10]){
            return false;
        }
        else if (!cartasFijadas[11]){
            return false;
        }
        else if (cartasFijadas[12]){
            if(!cartasFijadas[13]){
                return false;
            }
            else if(!cartasFijadas[14]){
                return false;
            }
        }
       return true;   
        
    }
    private boolean existeCarta(String cadena){

        switch(cadena.charAt(0)){
            case 'A': 
                break;
            case 'K':
                break;
            case 'Q':
                break;
            case 'J':
                break;  
            case 'T':
                break; 
            case '9':
                break;  
            case '8':
                break; 
            case '7':
                break;
            case '6':
                break;  
            case '5':
                break;
            case '4':
                break;
            case '3':
                break; 
            case '2':
                break;  
            default:
                return false;
        }
        switch(cadena.charAt(1)){
            case 'h': 
                break;  
            case 'd':
                break;  
            case 's':
                break;  
            case 'c':
                break; 
            default:
                return false;
        }
        
        if(cadena.length() != 2)
            return false;
        else 
            return true;
    }
    
    private void establecerIcono(String cadena){
        
        switch(numJugador){
            case 16: 
                jButtonRiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                break;
            case 15:
                jButtonTurn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                break;
            case 14: 
                jButtonFlop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[14] = true;
                break;
            case 13:
                jButtonFLop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[13] = true;
                break;
            case 12:
                jButtonFlop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[12] = true;
                break;
            case 11:
                jButtonPlayer6_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[11] = true;
                break;  
            case 10:
                jButtonPlayer6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[10] = true;
                break; 
            case 9:
                jButtonPlayer5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[9] = true;
                break;  
            case 8:
                jButtonPlayer5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[8] = true;
                break;  
            case 7:
                jButtonPlayer4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[7] = true;
                break;  
            case 6:
                jButtonPlayer4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[6] = true;
                break;  
            case 5:
                jButtonPlayer3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[5] = true;
                break;  
            case 4:
                jButtonPlayer3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[4] = true;
                break;
            case 3:
                jButtonPlayer2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[3] = true;
                break;  
            case 2:
                jButtonPlayer2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[2] = true;
                break;
            case 1:
                jButtonPlayer1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[1] = true;
                break;
            case 0:
                jButtonPlayer1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartasImg/" + cadena + ".jpg")));
                cartasFijadas[0] = true;
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCEquity;
    private javax.swing.JButton jButtonFLop2;
    private javax.swing.JButton jButtonFlop1;
    private javax.swing.JButton jButtonFlop3;
    private javax.swing.JButton jButtonFold1;
    private javax.swing.JButton jButtonFold2;
    private javax.swing.JButton jButtonFold3;
    private javax.swing.JButton jButtonFold4;
    private javax.swing.JButton jButtonFold5;
    private javax.swing.JButton jButtonFold6;
    private javax.swing.JButton jButtonPlayer1_1;
    private javax.swing.JButton jButtonPlayer1_2;
    private javax.swing.JButton jButtonPlayer2_1;
    private javax.swing.JButton jButtonPlayer2_2;
    private javax.swing.JButton jButtonPlayer3_1;
    private javax.swing.JButton jButtonPlayer3_2;
    private javax.swing.JButton jButtonPlayer4_1;
    private javax.swing.JButton jButtonPlayer4_2;
    private javax.swing.JButton jButtonPlayer5_1;
    private javax.swing.JButton jButtonPlayer5_2;
    private javax.swing.JButton jButtonPlayer6_1;
    private javax.swing.JButton jButtonPlayer6_2;
    private javax.swing.JButton jButtonRiver;
    private javax.swing.JButton jButtonTurn;
    private javax.swing.JButton jButton_Aplicar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Player1;
    private javax.swing.JTextField jTextField_Player2;
    private javax.swing.JTextField jTextField_Player3;
    private javax.swing.JTextField jTextField_Player4;
    private javax.swing.JTextField jTextField_Player5;
    private javax.swing.JTextField jTextField_Player6;
    // End of variables declaration//GEN-END:variables

   
}
