apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: empleado
  namespace: default
spec:
  hosts:
  - empleado
  http:
  - route:
    - destination:
        host: empleado
        subset: version-v1
    mirror:
      host: empleado
      subset: version-v2