apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python
  namespace: default
spec:
  hosts:
  - python
  http:
  - route:
    - destination:
        host: python
        subset: version-v1
    mirror:
      host: python
      subset: version-v2