apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: empleado
spec:
  hosts:
  - empleado
  http:
  - route:
    - destination:
        host: empleado
        subset: version-v1
      weight: 100