apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python
spec:
  hosts:
  - python
  http:
  - route:
    - destination:
        host: python
        subset: version-v1
      weight: 100