apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeMode: Filesystem
  storageClassName: mysql
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 10Gi
