apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
     app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
         claimName: mysql-pvc
      containers:
      - name: mysqldb
        image: mysql:5.7
        #imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpassword
              key: password
        - name: MYSQL_DATABASE
          value: db_personas
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql/


          