apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-web-app
spec:
  selector:
    matchLabels:
      app: my-php-web-app
  template:
    metadata:
      labels:
        app: my-php-web-app
    spec:
      containers:
        - name: my-php-web-app
          image: rauldieg/myrepository:my-php-web-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey